name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS }}
          plugin_achievements: yes
          plugin_achievements_threshold: D      # Display achievements with rank B or higher
          plugin_achievements_secrets: yes      # Display unlocked secrets achievements
          plugin_achievements_display: detailed  # Use compact display
          plugin_achievements_limit: 0          # Display all unlocked achievements (no limit)
          plugin_achievements_ignored: octonaut # Hide "octonaut" achievement
          plugin_achievements_only: explorer    # Display only "explorer" achievement (don't use with "ignored" option)
          plugin_activity: yes
          plugin_activity_limit: 100           # Limit to 5 events
          plugin_activity_load: 100          # Load up to 100 recent events from API (should be higher than "limit")
          plugin_activity_days: 0           # Keep only events from last 14 days (set to 0 for no limit)
          plugin_activity_filter: all        # Show all events (use table above to filter events types)
          plugin_activity_visibility: public # Only display public events
          plugin_activity_timestamps: yes    # Display events timestamps
          plugin_discussions: yes
          plugin_code: yes
          plugin_code_lines: 100               # Only display snippets with less than 12 lines
          plugin_code_load: 100               # Fetch 100 events from activity
          plugin_code_visibility: public, private      # Only display snippets from public activity
          plugin_code_languages: csharp, xaml   # Limit code snippets to JavaScript code
          plugin_contributors: yes
          plugin_contributors_base: ""               # Base reference (commit, tag, branch, etc.)
          plugin_contributors_head: main             # Head reference (commit, tag, branch, etc.)
          plugin_contributors_ignored: bot           # Ignore "bot" user
          plugin_contributors_contributions: yes     # Display number of contributions for each contributor
          plugin_contributors_sections: contributors # Display contributors sections
          plugin_contributors_categories: |          # A JSON mapping of labels by files edited
            {
              "📚 Documentation": ["README.md", "docs/**"],
              "💻 Code": ["main/**", "src/**", "feature/**"],
              "#️⃣ Others": ["*"]
            }
          plugin_followup: yes
          plugin_followup_sections: repositories, user # Display overall status of issues/pull requests created on user's repositories and created by user
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_from: 200       # Use 200 events to compute habits
          plugin_habits_days: 365        # Keep only events from last 14 days
          plugin_habits_facts: yes      # Display facts section
          plugin_habits_charts: yes     # Display charts section
          plugin_habits_trim: yes       # Trim unused hours on daily chart
          config_timezone: Asia/Manila # Set timezone
          plugin_introduction: yes
          plugin_introduction_title: no # Hide section title
          plugin_languages: yes
          plugin_languages_limit: 20                                     # Display up to 8 languages
          plugin_languages_sections: most-used, recently-used           # Display most used and recently used
          plugin_languages_colors: "csharp:green, xaml:blue, ..."  # Make most used languages orange and JavaScript red
          plugin_languages_details: bytes-size, percentage              # Additionally display total bytes size and percentage
          plugin_languages_threshold: 2%                                # Hides all languages less than 2%
          plugin_languages_indepth: no                                  # Get indepth stats (see documentation before enabling)
          plugin_languages_analysis_timeout: 15                         # Set maximum time for indepth analysis
          plugin_languages_categories: programming                      # Display only languages that match these categories in most-used section
          plugin_languages_recent_categories: markup, programming, data # Display only languages that match these categories in recently-used section
          plugin_languages_recent_load: 500                             # Load up to 500 events to compute recently used stats
          plugin_languages_recent_days: 7                               # Limit recently used stats to last week
          commits_authoring: echo_lumaque@memosoft.jp           # Surnames or email addresses used to identify your commits
          plugin_lines: yes
          plugin_notable_filter: stars:>0 # Only display repositories with 500 stars or more (syntax based on GitHub search query)
          plugin_notable_from: organization # Only display contributions within organization repositories
          plugin_notable_repositories: yes  # Display repositories name instead of only organization name
          plugin_notable_indepth: yes       # Gather additional informations about contributions
          plugin_people: yes
          plugin_people_types: followers, thanks     # Display followers and "thanks" sections
          plugin_people_limit: 28                    # Limit to 28 entries per section
          plugin_people_size: 28                     # Size in pixels of displayed avatars
          plugin_people_identicons: no               # Use avatars (do not use identicons)
          plugin_people_thanks: lowlighter, octocat  # Users that will be displayed in "thanks" section
          plugin_people_sponsors_custom: octocat     # Users that will be displayed additionally in "sponsors" section
          plugin_people_shuffle: yes                 # Shuffle for varied output
          plugin_reactions: yes
          plugin_reactions_limit: 200                  # Compute reactions over last 200 issue comments
          plugin_reactions_limit_issues: 100           # Compute reactions over last 100 issues/pull requests opened
          plugin_reactions_limit_discussions: 100      # Compute reactions over last 100 discussions
          plugin_reactions_limit_discussions_comments: 100 # Compute reactions over last 100 discussions comments
          plugin_reactions_days: 365                 # Compute reactions on issue comments posted less than 14 days ago
          plugin_reactions_display: absolute           # Display percentages based on the total amoun fetched
          plugin_reactions_details: count, percentage  # Display reactions count and percentage
          plugin_reactions_ignored: bot                # Ignore "bot" user
          plugin_repositories: yes
          plugin_repositories_featured: Memosoft-Japan/Spelling1, Memosoft-Japan/Money1, Memosoft-Japan/Azure-App, Memosoft-Japan/Azure-Functions, Memosoft-Japan/Azure-Tracking-Excel
          plugin_stars: yes
          plugin_stars_limit: 100
          plugin_traffic: yes
